<script type="text/javascript" src="http://localhost/ev/templates/assets/plugins/jquery/jquery.min.js"></script>
<script type="text/javascript" src="http://localhost/ev/templates/assets/plugins/popper/popper.min.js"></script>
<script type="text/javascript" src="http://localhost/ev/templates/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
<script type="text/javascript" src="http://localhost/ev/templates/assets/js/jquery.slimscroll.js"></script>
<script type="text/javascript" src="http://localhost/ev/templates/assets/js/waves.js"></script>
<script type="text/javascript" src="http://localhost/ev/templates/assets/js/sidebarmenu.js"></script>
<script type="text/javascript" src="http://localhost/ev/templates/assets/plugins/sticky-kit-master/dist/sticky-kit.min.js"></script>
<script type="text/javascript" src="http://localhost/ev/templates/assets/plugins/sparkline/jquery.sparkline.min.js"></script>
<script type="text/javascript" src="http://localhost/ev/templates/assets/js/custom.min.js"></script>
<script type="text/javascript" src="http://localhost/ev/templates/assets/plugins/chartist-js/dist/chartist.min.js"></script>
<script type="text/javascript" src="http://localhost/ev/templates/assets/plugins/chartist-plugin-tooltip-master/dist/chartist-plugin-tooltip.min.js"></script>
<script type="text/javascript" src="http://localhost/ev/templates/assets/plugins/d3/d3.min.js"></script>
<script type="text/javascript" src="http://localhost/ev/templates/assets/plugins/c3-master/c3.min.js"></script>
<script type="text/javascript" src="http://localhost/ev/templates/assets/js/dashboard4.js"></script>
<script type="text/javascript" src="http://localhost/ev/templates/assets/plugins/styleswitcher/jQuery.style.switcher.js"></script>
<script type="text/javascript" src="http://localhost/ev/templates/assets/plugins/select2/dist/js/select2.full.min.js"></script>
<script type="text/javascript" src="http://localhost/ev/templates/assets/plugins/bootstrap-select/bootstrap-select.min.js"></script>
<script type="text/javascript" src="http://localhost/ev/templates/assets/plugins/multiselect/js/jquery.multi-select.js"></script>
